name: ci-test
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: apt-get deps
        run: sudo apt-get install -y build-essential docker-compose firefox mariadb-client
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: echo 'foo' > adfice_mariadb_root_password
      - run: echo 'foo' > adfice_mariadb_user_password
      - run: make check
