name: ci-test
on:
  push: {}
  pull_request: {}
  schedule:
#             ┌───────────── minute (0 - 59)
#             │  ┌───────────── hour (0 - 23)
#             │  │ ┌───────────── day of the month (1 - 31)
#             │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#             │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#             │  │ │ │ │
#             │  │ │ │ │
#             │  │ │ │ │
#             *  * * * *
    - cron:  '7 10 * * 6' # every Saturday at 09:07 UTC

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: apt-get deps
        run: sudo apt-get install -y
           build-essential
           docker-compose
           firefox
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: echo 'foo' > adfice_mariadb_root_password
      - run: echo 'foo' > adfice_mariadb_user_password
      - run: echo 'foo' > valportaal_mariadb_root_password
      - run: echo 'foo' > valportaal_mariadb_user_password
      - run: >
          TEST_BROWSER="chrome:headless"
          VM_PORT_SSH=55022
          VM_PORT_HTTP=55080
          VM_PORT_HTTPS=55443
          make check
      - run: git submodule update --init --recursive
      - run: echo 'foo' > centos-vm/vm_root_password
      - run: >
          TEST_BROWSER="chrome:headless"
          VM_PORT_SSH=55022
          VM_PORT_HTTP=55080
          VM_PORT_HTTPS=55443
          make -j1 vm-check
