name: ci-test
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: apt-get deps
        run: sudo apt-get install -y
           build-essential
           docker-compose
           firefox
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: echo 'foo' > adfice_mariadb_root_password
      - run: echo 'foo' > adfice_mariadb_user_password
      - run: echo 'foo' > valportaal_mariadb_root_password
      - run: echo 'foo' > valportaal_mariadb_user_password
      - run: >
          VM_PORT_SSH=55022
          VM_PORT_HTTP=55080
          VM_PORT_HTTPS=55443
          make check
      - run: >
          VM_PORT_SSH=55022
          VM_PORT_HTTP=55080
          VM_PORT_HTTPS=55443
          make vm-check
