name: ci-test
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: make check
